services:
  db:
    image: postgres:alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cinemaDB

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  backend_app:
    build:
      context: ./backend
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      # Database
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cinemaDB
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: admin
