/**
 * Cinema Service API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Podstawowe informacje o filmie
 */
export interface MovieSimpleDto {
  /**
   * ID filmu
   */
  id: number;
  /**
   * Tytuł filmu
   */
  title: string;
}
