/**
 * Cinema Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Odpowiedź po przetworzeniu płatności
 */
export interface PaymentResponse { 
    /**
     * Czy płatność się powiodła
     */
    success?: boolean;
    /**
     * Komunikat informacyjny
     */
    message?: string;
}

