/**
 * Cinema Service API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SeatDto } from './seatDto';
import { RoomDto } from './roomDto';
import { ScreeningDetailsResponseDuration } from './screeningDetailsResponseDuration';
import { MovieSimpleDto } from './movieSimpleDto';

/**
 * Szczegółowe informacje o seansie filmowym
 */
export interface ScreeningDetailsResponse {
  /**
   * ID seansu
   */
  id: number;
  /**
   * Informacje o filmie
   */
  movie: MovieSimpleDto;
  /**
   * Informacje o sali
   */
  room: RoomDto;
  /**
   * Czas rozpoczęcia
   */
  startTime: string;
  duration: number;
  /**
   * Lista dostępnych miejsc
   */
  seats: Array<SeatDto>;
}
