/**
 * Cinema Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScreeningSummaryDtoDurationUnitsInner } from './screeningSummaryDtoDurationUnitsInner';


export interface ScreeningSummaryDtoDuration { 
    seconds?: number;
    zero?: boolean;
    nano?: number;
    negative?: boolean;
    positive?: boolean;
    units?: Array<ScreeningSummaryDtoDurationUnitsInner>;
}

