/**
 * Cinema Service API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Informacje o miejscu w sali kinowej
 */
export interface SeatDto {
  /**
   * ID miejsca
   */
  id: number;
  /**
   * Numer rzędu
   */
  rowNumber: number;
  /**
   * Numer kolumny
   */
  columnNumber: number;
  /**
   * Numer miejsca
   */
  seatNumber: number;
  /**
   * Czy miejsce jest dostępne
   */
  available: boolean;
}
