/**
 * Cinema Service API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Odpowiedź po potwierdzeniu rezerwacji zawierająca dane biletu
 */
export interface TicketResponse {
  /**
   * Numery miejsc
   */
  seatNumbers: Array<number>;
  /**
   * Tytuł filmu
   */
  movieTitle: string;
  /**
   * Data i godzina rozpoczęcia seansu
   */
  screeningStartTime: string;
  /**
   * Unikalny identyfikator biletu
   */
  ticketId: string;
  /**
   * Status biletu
   */
  status: TicketResponse.StatusEnum;
  /**
   * Email osoby rezerwującej
   */
  email: string;
  /**
   * Imię i nazwisko właściciela biletu
   */
  ticketOwner: string;
  /**
   * Łączna cena biletu
   */
  price: number;
}
export namespace TicketResponse {
  export const StatusEnum = {
    Valid: 'VALID',
    Used: 'USED',
    Expired: 'EXPIRED',
    ToBeCalculated: 'TO_BE_CALCULATED',
  } as const;
  export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];
}
