/**
 * Cinema Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Dane wymagane do przetworzenia płatności
 */
export interface PaymentRequest { 
    /**
     * Identyfikator użytkownika
     */
    userId?: number;
    /**
     * Kwota płatności
     */
    amount?: number;
    /**
     * Metoda płatności
     */
    method?: string;
}

