/**
 * Cinema Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Dane wymagane do rezerwacji miejsc na seansie
 */
export interface ReservationRequest { 
    /**
     * ID seansu, na który ma zostać dokonana rezerwacja
     */
    screeningId: number;
    /**
     * Lista identyfikatorów miejsc do rezerwacji
     */
    seatIds: Array<number>;
    /**
     * Adres email osoby rezerwującej
     */
    email: string;
    /**
     * Imię osoby rezerwującej
     */
    name: string;
    /**
     * Nazwisko osoby rezerwującej
     */
    surname: string;
}

