/**
 * Cinema Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScreeningSummaryDtoDuration } from './screeningSummaryDtoDuration';


export interface ScreeningSummaryDto { 
    id?: number;
    startTime?: string;
    duration?: ScreeningSummaryDtoDuration;
}

