spring:
  application:
    name: backend
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://db:5432/cinemaDB
    username: user
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
#  docker:
#    compose:
#      file: ../compose.yaml