spring:
  application:
    name: backend
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://db:5432/cinemaDB
    username: user
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  docker:
    compose:
      file: ../compose.yaml
  security:
    oauth2:
      resource-server:
        jwt:
          public-key: classpath:publicKey.pem
          private-key: classpath:privateKey.pem
  logging:
    level:
      root: info
      com.psiw.proj.backend: debug
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace
    file:
      name: logs/backend.log
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - [%thread] %-5level %logger{36} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} - [%thread] %-5level %logger{36} - %msg%n"